### PR TITLE
Adding copyright and license notification for multiregexp-derived code

### PR DESCRIPTION
**Pull request by fernomac**
Addresses #2.

### CODE REVIEW

**Comment by jamesward** [comment]
Can't we switch to using the Maven dep instead?

**Comment by fernomac** [comment]
I'll leave that up to @tatu-at-sfdc; it looks like a couple utility classes, so may not be worth bringing in the whole package as a dependency. The other way to go would be to do a clean-room rewrite.

**Comment by tatu-at-sfdc** [comment]
@jamesward Automaton itself is normal Maven dependency (although shaded in result), see `gorp-core/pom.xml`. But unfortunately 2 additional classes are needed to work around class inheritance challenge; they reside in same package but are just adapter pieces added similar to how extension works from within Automaton.

Put another way: this is not taking running code from Automaton as cut'n paste but adding class in necessary package to allow sub-classing.

Does this make more sense? I did add mentions in classes to show where the idea for work-around came.

**Comment by tatu-at-sfdc** [comment]
Actually. Let me take that back. I am missing references to `multiregexp`, question was NOT about Automaton itself.

**Pull request merged**
